### ISSUE TITLE
Update branch protection rules

### ISSUE THREAD

**Issue by klauer** [pcdshub/device_config#34]
* `deploy` is our as-deployed, unreviewed, production configuration
* `master` is our reviewed and approved reference

Rules:
* `master` should be protected from accidental pushes
* Force push should be disabled

**Comment by ZLLentz** [comment]
`deploy` also needs to be protected from accidental pushes

**Comment by klauer** [comment]
`deploy` is now on the list of branch protection rules
`master` requires review and force push is disabled
