### ISSUE TITLE
Branch `backup` missing?

### ISSUE THREAD

**Issue by klauer** [pcdshub/device_config#6]
`README.md` indicates the `backup` branch should exist. Is the cron job not running or is this outdated information?

**Comment by ZLLentz** [comment]
I don't remember there actually ever being a `backup` branch, but I know there was a cron running that updated the `deploy` branch.

**Comment by ZryletTC** [comment]
Bump. Should I setup a backup cron job? Should be pretty easy and can run on Travis.

**Comment by ZLLentz** [comment]
Strangely, we've always called this branch `deploy` instead of backup. The old cron job is likely dead, it used to run on `pscron` and simply commit and push to the `deploy` branch here. I'm not sure if a backup from Travis is useful since it's already in git if it made it to Travis.

**Comment by ZryletTC** [comment]
Ahh, that makes sense. So we just need a new cronjob and updated README.
